/**
 * PDF Report Generator for PVRE Research Results
 * Generates comprehensive PDF reports from research data.
 */

import jsPDF from 'jspdf';
import type { CommunityVoiceResult } from '@/app/api/research/community-voice/route';
import type { CompetitorIntelligenceResult } from '@/app/api/research/competitor-intelligence/route';
import type { ViabilityVerdict } from '@/lib/analysis/viability-calculator';

export interface ReportData {
  hypothesis: string;
  createdAt: string;
  viability: ViabilityVerdict;
  communityVoice?: CommunityVoiceResult;
  competitors?: CompetitorIntelligenceResult;
}

// Color palette
const COLORS = {
  primary: [59, 130, 246] as [number, number, number],      // Blue
  success: [34, 197, 94] as [number, number, number],       // Green
  warning: [234, 179, 8] as [number, number, number],       // Yellow
  danger: [239, 68, 68] as [number, number, number],        // Red
  orange: [249, 115, 22] as [number, number, number],       // Orange
  gray: [107, 114, 128] as [number, number, number],        // Gray
  lightGray: [243, 244, 246] as [number, number, number],   // Light gray
  darkGray: [55, 65, 81] as [number, number, number],       // Dark gray
};

export function generatePDFReport(data: ReportData): jsPDF {
  const doc = new jsPDF();
  let y = 20;
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;
  let pageNumber = 1;

  // Helper function for text wrapping
  const addWrappedText = (text: string, fontSize: number, maxWidth: number = contentWidth) => {
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.45) + 4;
  };

  // Helper for new page check
  const checkNewPage = (neededSpace: number = 40) => {
    if (y > pageHeight - neededSpace) {
      addPageFooter();
      doc.addPage();
      pageNumber++;
      y = 30;
      addPageHeader();
    }
  };

  // Add page header (except first page)
  const addPageHeader = () => {
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 0, pageWidth, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text('PVRE Research Report', margin, 15);
    doc.setTextColor(0);
  };

  // Add page footer with page number
  const addPageFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text(`Page ${pageNumber}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text('Generated by PVRE - Pre-Validation Research Engine', margin, pageHeight - 10);
    doc.setTextColor(0);
  };

  // Draw score bar
  const drawScoreBar = (score: number, maxScore: number, x: number, barY: number, width: number, height: number = 8) => {
    const percentage = score / maxScore;
    const color = percentage >= 0.7 ? COLORS.success :
                  percentage >= 0.5 ? COLORS.warning :
                  percentage >= 0.3 ? COLORS.orange : COLORS.danger;

    // Background
    doc.setFillColor(...COLORS.lightGray);
    doc.roundedRect(x, barY, width, height, 2, 2, 'F');

    // Fill
    doc.setFillColor(...color);
    const fillWidth = Math.max(width * percentage, 4);
    doc.roundedRect(x, barY, fillWidth, height, 2, 2, 'F');
  };

  // Add section header (compact design)
  const addSectionHeader = (title: string, icon?: string) => {
    checkNewPage(40);
    y += 3;
    doc.setFillColor(...COLORS.lightGray);
    doc.rect(margin - 5, y - 4, contentWidth + 10, 10, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.darkGray);
    doc.text(icon ? `${icon}  ${title}` : title, margin, y + 2);
    doc.setTextColor(0);
    y += 12;
  };

  // === PAGE 1: Executive Summary ===

  // Header accent bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 6, 'F');

  y = 25;
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Research Report', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.gray);
  doc.text(`Generated: ${data.createdAt}`, margin, y);
  y += 15;

  // Hypothesis box - modern card design with accent border
  const accentWidth = 4;
  const innerPadding = 15;
  doc.setFontSize(10);
  const hypothesisLines = doc.splitTextToSize(data.hypothesis, contentWidth - accentWidth - (innerPadding * 2) - 5);
  const lineHeight = 5;
  const hypothesisBoxHeight = 12 + (hypothesisLines.length * lineHeight) + 12;

  // Main box background
  doc.setFillColor(250, 251, 252);
  doc.setDrawColor(230, 232, 236);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentWidth, hypothesisBoxHeight, 4, 4, 'FD');

  // Left accent bar (primary color)
  doc.setFillColor(...COLORS.primary);
  doc.roundedRect(margin, y, accentWidth, hypothesisBoxHeight, 4, 0, 'F');
  doc.rect(margin + 2, y, 2, hypothesisBoxHeight, 'F'); // Square off inner edge

  // Label
  y += 10;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gray);
  doc.text('HYPOTHESIS', margin + accentWidth + innerPadding, y);

  // Hypothesis text
  y += 6;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(hypothesisLines, margin + accentWidth + innerPadding, y);
  y += hypothesisLines.length * lineHeight + 8;

  // Viability Verdict Box
  const verdictColor = data.viability.verdict === 'strong' ? COLORS.success :
                       data.viability.verdict === 'mixed' ? COLORS.warning :
                       data.viability.verdict === 'weak' ? COLORS.orange :
                       COLORS.danger;

  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...verdictColor);
  doc.setLineWidth(2);
  doc.roundedRect(margin, y, contentWidth, 55, 4, 4, 'FD');

  y += 12;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gray);
  doc.text('VIABILITY VERDICT', margin + 10, y);

  // Big score
  y += 15;
  doc.setFontSize(36);
  doc.setTextColor(...verdictColor);
  doc.text(`${data.viability.overallScore.toFixed(1)}`, margin + 10, y);

  doc.setFontSize(14);
  doc.text('/10', margin + 35, y);

  // Verdict label
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(data.viability.verdictLabel, margin + 60, y - 5);

  // Score bar
  drawScoreBar(data.viability.overallScore, 10, margin + 60, y + 2, contentWidth - 70, 6);

  y += 15;
  doc.setTextColor(0);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const descLines = doc.splitTextToSize(data.viability.verdictDescription, contentWidth - 20);
  doc.text(descLines.slice(0, 2), margin + 10, y);
  y += 25;

  // === TWO-AXIS VERDICT (Report Redesign v6) ===
  if (data.viability.hypothesisConfidence && data.viability.marketOpportunity) {
    const hypoConf = data.viability.hypothesisConfidence;
    const mktOpp = data.viability.marketOpportunity;

    checkNewPage(70);
    y += 5;

    // Section header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.darkGray);
    doc.text('Two-Axis Assessment', margin, y);
    y += 8;

    const boxWidth = (contentWidth - 10) / 2;
    const boxHeight = 55;

    // Hypothesis Confidence box
    const hypoColor = hypoConf.level === 'high' ? COLORS.success :
                      hypoConf.level === 'partial' ? COLORS.warning : COLORS.danger;
    doc.setFillColor(250, 251, 252);
    doc.setDrawColor(...hypoColor);
    doc.setLineWidth(1.5);
    doc.roundedRect(margin, y, boxWidth, boxHeight, 4, 4, 'FD');

    // Hypothesis Confidence content
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.gray);
    doc.text('HYPOTHESIS CONFIDENCE', margin + 8, y + 10);

    doc.setFontSize(24);
    doc.setTextColor(...hypoColor);
    doc.text(`${hypoConf.score.toFixed(1)}`, margin + 8, y + 28);

    doc.setFontSize(10);
    doc.text(`/10`, margin + 32, y + 28);

    // Level badge
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(hypoConf.level.toUpperCase(), margin + 50, y + 25);

    // Description
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    const hypoDesc = hypoConf.level === 'high' ? 'Strong evidence for your hypothesis' :
                     hypoConf.level === 'partial' ? 'Some signals found, explore adjacent' :
                     'Consider adjacent opportunities';
    doc.text(hypoDesc, margin + 8, y + 45);

    // Market Opportunity box
    const mktColor = mktOpp.level === 'strong' ? COLORS.success :
                     mktOpp.level === 'moderate' ? COLORS.warning : COLORS.danger;
    doc.setDrawColor(...mktColor);
    doc.roundedRect(margin + boxWidth + 10, y, boxWidth, boxHeight, 4, 4, 'FD');

    // Market Opportunity content
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.gray);
    doc.text('MARKET OPPORTUNITY', margin + boxWidth + 18, y + 10);

    doc.setFontSize(24);
    doc.setTextColor(...mktColor);
    doc.text(`${mktOpp.score.toFixed(1)}`, margin + boxWidth + 18, y + 28);

    doc.setFontSize(10);
    doc.text(`/10`, margin + boxWidth + 42, y + 28);

    // Level badge
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(mktOpp.level.toUpperCase(), margin + boxWidth + 60, y + 25);

    // Description
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    const mktDesc = mktOpp.level === 'strong' ? 'Active market with validated demand' :
                    mktOpp.level === 'moderate' ? 'Market exists, consider positioning' :
                    'Limited market signals found';
    doc.text(mktDesc, margin + boxWidth + 18, y + 45);

    y += boxHeight + 15;
    doc.setTextColor(0);
  }

  // Dimension scores grid
  y += 5;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Dimension Breakdown', margin, y);
  y += 10;

  const dimColWidth = contentWidth / 2;
  data.viability.dimensions.forEach((dim, i) => {
    const col = i % 2;
    const xPos = margin + col * dimColWidth;

    if (col === 0 && i > 0) y += 22;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    doc.text(`${dim.name} (${Math.round(dim.weight * 100)}%)`, xPos, y);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(`${dim.score.toFixed(1)}/10`, xPos + dimColWidth - 35, y);

    // Mini score bar
    drawScoreBar(dim.score, 10, xPos, y + 3, dimColWidth - 40, 5);
  });
  y += 30;

  // Dealbreakers
  if (data.viability.dealbreakers.length > 0) {
    checkNewPage(50);
    doc.setFillColor(254, 242, 242);
    doc.setDrawColor(...COLORS.danger);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentWidth, 8 + data.viability.dealbreakers.length * 8, 3, 3, 'FD');

    y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.danger);
    doc.text('DEALBREAKERS', margin + 5, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(0);
    data.viability.dealbreakers.forEach(db => {
      const lines = doc.splitTextToSize(`• ${db}`, contentWidth - 15);
      doc.text(lines[0], margin + 5, y);
      y += 7;
    });
    y += 10;
  }

  // Recommendations
  if (data.viability.recommendations.length > 0) {
    checkNewPage(60);
    addSectionHeader('Recommendations');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    data.viability.recommendations.forEach((rec, i) => {
      checkNewPage(20);
      const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, contentWidth);
      doc.text(lines, margin, y);
      y += lines.length * 4 + 4;
    });
  }

  // === PAGE 2: Community Voice (if available) ===
  if (data.communityVoice) {
    addPageFooter();
    doc.addPage();
    pageNumber++;
    y = 30;
    addPageHeader();

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text('Community Voice Analysis', margin, y);
    y += 15;

    // Pain Summary Cards
    const painSummary = data.communityVoice.painSummary;
    const cardWidth = (contentWidth - 10) / 3;

    // Total Signals card
    doc.setFillColor(...COLORS.lightGray);
    doc.roundedRect(margin, y, cardWidth, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text('Total Signals', margin + 5, y + 8);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.darkGray);
    doc.text(String(painSummary.totalSignals), margin + 5, y + 20);

    // High Intensity card
    doc.setFillColor(254, 242, 242);
    doc.roundedRect(margin + cardWidth + 5, y, cardWidth, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.danger);
    doc.text('High Intensity', margin + cardWidth + 10, y + 8);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(String(painSummary.highIntensityCount), margin + cardWidth + 10, y + 20);

    // WTP Signals card
    doc.setFillColor(236, 253, 245);
    doc.roundedRect(margin + (cardWidth + 5) * 2, y, cardWidth, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.success);
    doc.text('WTP Signals', margin + (cardWidth + 5) * 2 + 5, y + 8);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(String(painSummary.willingnessToPayCount), margin + (cardWidth + 5) * 2 + 5, y + 20);

    y += 35;

    // Top Subreddits
    addSectionHeader('Top Subreddits');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);
    painSummary.topSubreddits.slice(0, 5).forEach(sub => {
      doc.text(`r/${sub.name}`, margin, y);
      doc.text(`${sub.count} signals`, margin + 80, y);
      y += 6;
    });
    y += 5;

    // Themes (condensed to top 3)
    if (data.communityVoice.themeAnalysis?.themes) {
      addSectionHeader('Top Pain Themes');
      doc.setFontSize(9);
      data.communityVoice.themeAnalysis.themes.slice(0, 3).forEach(theme => {
        checkNewPage(25);
        doc.setFont('helvetica', 'bold');
        const intensityColor = theme.intensity === 'high' ? COLORS.danger :
                              theme.intensity === 'medium' ? COLORS.warning : COLORS.gray;
        doc.setTextColor(...intensityColor);
        doc.text(`[${theme.intensity.toUpperCase()}]`, margin, y);
        doc.setTextColor(0);
        doc.text(theme.name, margin + 25, y);
        y += 5;
        doc.setFont('helvetica', 'normal');
        const descLines = doc.splitTextToSize(theme.description, contentWidth);
        doc.text(descLines.slice(0, 2), margin, y);
        y += descLines.slice(0, 2).length * 4 + 4;
      });
    }

    // Key Quotes
    if (data.communityVoice.themeAnalysis?.keyQuotes && data.communityVoice.themeAnalysis.keyQuotes.length > 0) {
      checkNewPage(60);
      addSectionHeader('Key Quotes');
      doc.setFontSize(9);
      data.communityVoice.themeAnalysis.keyQuotes.slice(0, 3).forEach(q => {
        checkNewPage(25);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, y - 3, contentWidth, 18, 2, 2, 'F');
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...COLORS.darkGray);
        const quoteLines = doc.splitTextToSize(`"${q.quote}"`, contentWidth - 10);
        doc.text(quoteLines.slice(0, 2), margin + 5, y + 3);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.gray);
        doc.text(`— ${q.source}`, margin + 5, y + 13);
        doc.setTextColor(0);
        doc.setFontSize(9);
        y += 22;
      });
    }

    // Customer Language Bank
    const customerLanguage = data.communityVoice.themeAnalysis?.customerLanguage;
    const alternativesMentioned = data.communityVoice.themeAnalysis?.alternativesMentioned;
    if ((customerLanguage && customerLanguage.length > 0) || (alternativesMentioned && alternativesMentioned.length > 0)) {
      checkNewPage(60);
      addSectionHeader('Customer Language Bank');
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.gray);
      doc.text('Use these exact phrases in your marketing, landing pages, and customer interviews', margin, y);
      y += 8;

      // Problem phrases
      if (customerLanguage && customerLanguage.length > 0) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.darkGray);
        doc.text('How They Describe The Problem:', margin, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        const phrases = customerLanguage.slice(0, 6).map(p => `"${p}"`).join('  •  ');
        const phraseLines = doc.splitTextToSize(phrases, contentWidth);
        doc.text(phraseLines.slice(0, 3), margin, y);
        y += phraseLines.slice(0, 3).length * 4 + 6;
      }

      // Tools mentioned
      if (alternativesMentioned && alternativesMentioned.length > 0) {
        checkNewPage(20);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.darkGray);
        doc.text('Tools & Alternatives Mentioned:', margin, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        const tools = alternativesMentioned.slice(0, 8).join('  •  ');
        const toolLines = doc.splitTextToSize(tools, contentWidth);
        doc.text(toolLines.slice(0, 2), margin, y);
        y += toolLines.slice(0, 2).length * 4 + 6;
      }
      y += 5;
    }

    // Adjacent Opportunities (shown when hypothesis confidence is low or partial)
    if (data.viability.hypothesisConfidence &&
        (data.viability.hypothesisConfidence.level === 'low' || data.viability.hypothesisConfidence.level === 'partial') &&
        data.communityVoice.themeAnalysis?.themes) {
      // Find contextual themes (non-core) as pivot candidates
      const contextualThemes = data.communityVoice.themeAnalysis.themes
        .filter((t: { tier?: string }) => t.tier === 'contextual')
        .slice(0, 3);

      if (contextualThemes.length > 0) {
        checkNewPage(80);
        addSectionHeader('Adjacent Opportunities');
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...COLORS.gray);
        doc.text('Your specific hypothesis wasn\'t the most prominent topic. Consider these pivot candidates:', margin, y);
        y += 10;

        contextualThemes.forEach((theme: { name: string; description: string; frequency: number; intensity: string }, i: number) => {
          checkNewPage(30);
          doc.setFillColor(248, 250, 252);
          doc.roundedRect(margin, y - 3, contentWidth, 22, 2, 2, 'F');

          // Intensity indicator
          const intensityColor = theme.intensity === 'high' ? COLORS.danger :
                                theme.intensity === 'medium' ? COLORS.warning : COLORS.gray;
          doc.setFillColor(...intensityColor);
          doc.rect(margin, y - 3, 3, 22, 'F');

          doc.setFontSize(10);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(...COLORS.darkGray);
          doc.text(`${i + 1}. ${theme.name}`, margin + 8, y + 5);

          doc.setFontSize(8);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(...COLORS.gray);
          doc.text(`${theme.frequency} signals`, margin + contentWidth - 40, y + 5);

          doc.setTextColor(0);
          const descLines = doc.splitTextToSize(theme.description, contentWidth - 20);
          doc.text(descLines.slice(0, 1), margin + 8, y + 14);

          y += 28;
        });

        // Pivot suggestion
        doc.setFillColor(236, 253, 245);
        doc.roundedRect(margin, y, contentWidth, 15, 2, 2, 'F');
        y += 10;
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.success);
        doc.text('TIP:', margin + 5, y);
        doc.setFont('helvetica', 'normal');
        doc.text('Interview users about these adjacent problems - your original hypothesis may emerge naturally.', margin + 20, y);
        doc.setTextColor(0);
        y += 15;
      }
    }

    // Market Sizing
    if (data.communityVoice.marketSizing) {
      checkNewPage(80);
      addSectionHeader('Market Sizing (TAM/SAM/SOM)');
      const ms = data.communityVoice.marketSizing;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');

      // TAM
      doc.setFont('helvetica', 'bold');
      doc.text('TAM:', margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.tam.value.toLocaleString()} potential customers`, margin + 25, y);
      y += 5;
      doc.setTextColor(...COLORS.gray);
      doc.text(ms.tam.description, margin + 25, y);
      doc.setTextColor(0);
      y += 8;

      // SAM
      doc.setFont('helvetica', 'bold');
      doc.text('SAM:', margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.sam.value.toLocaleString()} serviceable customers`, margin + 25, y);
      y += 5;
      doc.setTextColor(...COLORS.gray);
      doc.text(ms.sam.description, margin + 25, y);
      doc.setTextColor(0);
      y += 8;

      // SOM
      doc.setFont('helvetica', 'bold');
      doc.text('SOM:', margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.som.value.toLocaleString()} obtainable customers`, margin + 25, y);
      y += 5;
      doc.setTextColor(...COLORS.gray);
      doc.text(ms.som.description, margin + 25, y);
      doc.setTextColor(0);
      y += 12;

      // MSC Analysis
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(margin, y, contentWidth, 22, 2, 2, 'F');
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.text('To reach your MSC:', margin + 5, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.mscAnalysis.customersNeeded.toLocaleString()} customers needed (${ms.mscAnalysis.penetrationRequired.toFixed(1)}% penetration)`, margin + 60, y);
      y += 7;
      const achieveColor = ms.mscAnalysis.achievability === 'highly_achievable' || ms.mscAnalysis.achievability === 'achievable'
        ? COLORS.success : ms.mscAnalysis.achievability === 'challenging' ? COLORS.warning : COLORS.danger;
      doc.setTextColor(...achieveColor);
      doc.text(`Achievability: ${ms.mscAnalysis.achievability.replace('_', ' ')}`, margin + 5, y);
      doc.setTextColor(0);
      y += 15;
    }

    // Timing
    if (data.communityVoice.timing) {
      checkNewPage(70);
      addSectionHeader('Timing Analysis');
      const timing = data.communityVoice.timing;

      // Score and trend
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Score: ${timing.score.toFixed(1)}/10`, margin, y);
      const trendColor = timing.trend === 'rising' ? COLORS.success :
                         timing.trend === 'stable' ? COLORS.warning : COLORS.danger;
      doc.setTextColor(...trendColor);
      doc.text(`Trend: ${timing.trend}`, margin + 50, y);
      doc.setTextColor(0);
      doc.text(`Window: ${timing.timingWindow}`, margin + 100, y);
      y += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      addWrappedText(timing.verdict, 9);
      y += 3;

      // Tailwinds
      if (timing.tailwinds.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.success);
        doc.text('Tailwinds:', margin, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        timing.tailwinds.slice(0, 3).forEach(tw => {
          const text = `+ ${tw.signal}: ${tw.description.slice(0, 70)}${tw.description.length > 70 ? '...' : ''}`;
          doc.text(text, margin + 5, y);
          y += 6;
        });
      }

      // Headwinds
      if (timing.headwinds.length > 0) {
        y += 3;
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.danger);
        doc.text('Headwinds:', margin, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        timing.headwinds.slice(0, 3).forEach(hw => {
          const text = `- ${hw.signal}: ${hw.description.slice(0, 70)}${hw.description.length > 70 ? '...' : ''}`;
          doc.text(text, margin + 5, y);
          y += 6;
        });
      }
    }

    // Interview Questions
    if (data.communityVoice.interviewQuestions) {
      addPageFooter();
      doc.addPage();
      pageNumber++;
      y = 30;
      addPageHeader();

      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.primary);
      doc.text('Interview Questions', margin, y);
      y += 5;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.gray);
      doc.text('Based on "The Mom Test" principles - focus on past behavior, not hypotheticals', margin, y);
      doc.setTextColor(0);
      y += 15;

      const sections = [
        { title: 'Context Questions', questions: data.communityVoice.interviewQuestions.contextQuestions, color: COLORS.primary },
        { title: 'Problem Exploration', questions: data.communityVoice.interviewQuestions.problemQuestions, color: COLORS.orange },
        { title: 'Solution Testing', questions: data.communityVoice.interviewQuestions.solutionQuestions, color: COLORS.success }
      ];

      sections.forEach(section => {
        checkNewPage(50);
        doc.setFillColor(...section.color);
        doc.rect(margin, y, 3, 10, 'F');
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.darkGray);
        doc.text(section.title, margin + 8, y + 7);
        y += 15;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        section.questions.forEach((q, i) => {
          checkNewPage(15);
          const lines = doc.splitTextToSize(`${i + 1}. ${q}`, contentWidth - 10);
          doc.text(lines, margin + 5, y);
          y += lines.length * 4 + 4;
        });
        y += 8;
      });
    }
  }

  // === PAGE: Competitors (if available) ===
  if (data.competitors) {
    addPageFooter();
    doc.addPage();
    pageNumber++;
    y = 30;
    addPageHeader();

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text('Competitive Landscape', margin, y);
    y += 15;

    // Competition Score
    if (data.competitors.competitionScore) {
      const cs = data.competitors.competitionScore;
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(margin, y, contentWidth, 30, 3, 3, 'F');

      y += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.gray);
      doc.text('COMPETITION SCORE', margin + 5, y);

      const scoreColor = cs.score >= 7 ? COLORS.success : cs.score >= 5 ? COLORS.warning : cs.score >= 3 ? COLORS.orange : COLORS.danger;
      doc.setFontSize(24);
      doc.setTextColor(...scoreColor);
      doc.text(`${cs.score.toFixed(1)}/10`, margin + 75, y);

      drawScoreBar(cs.score, 10, margin + 110, y - 6, contentWidth - 120, 8);

      y += 10;
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.gray);
      doc.text(`Data quality: ${cs.confidence}`, margin + 5, y);
      doc.setTextColor(0);
      y += 15;
    }

    // Market Overview
    if (data.competitors.marketOverview) {
      addSectionHeader('Market Overview');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      addWrappedText(data.competitors.marketOverview.summary, 9);
      doc.text(`Market Maturity: ${data.competitors.marketOverview.maturityLevel}`, margin, y);
      y += 10;
    }

    // Competitors
    addSectionHeader('Key Competitors');

    data.competitors.competitors.slice(0, 5).forEach(comp => {
      checkNewPage(45);

      // Threat level color bar
      const threatColor = comp.threatLevel === 'high' ? COLORS.danger :
                         comp.threatLevel === 'medium' ? COLORS.warning : COLORS.success;
      doc.setFillColor(...threatColor);
      doc.rect(margin, y, 3, 25, 'F');

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text(comp.name, margin + 8, y + 5);

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...threatColor);
      doc.text(`${comp.threatLevel} threat`, margin + 8 + doc.getTextWidth(comp.name) + 5, y + 5);
      doc.setTextColor(0);

      y += 10;
      doc.setFontSize(8);
      const descLines = doc.splitTextToSize(comp.description, contentWidth - 15);
      doc.text(descLines.slice(0, 2), margin + 8, y);
      y += descLines.slice(0, 2).length * 3.5 + 3;

      if (comp.strengths && comp.strengths.length > 0) {
        doc.setTextColor(...COLORS.success);
        doc.text('+ ' + comp.strengths.slice(0, 2).join(', ').slice(0, 80), margin + 8, y);
        y += 5;
      }
      if (comp.weaknesses && comp.weaknesses.length > 0) {
        doc.setTextColor(...COLORS.danger);
        doc.text('- ' + comp.weaknesses.slice(0, 2).join(', ').slice(0, 80), margin + 8, y);
        y += 5;
      }
      doc.setTextColor(0);
      y += 8;
    });

    // Gap Analysis
    if (data.competitors.gaps && data.competitors.gaps.length > 0) {
      checkNewPage(60);
      addSectionHeader('Market Gaps & Opportunities');
      doc.setFontSize(9);
      data.competitors.gaps.slice(0, 4).forEach(gap => {
        checkNewPage(25);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.success);
        doc.text(`[${gap.opportunity.toUpperCase()}]`, margin, y);
        doc.setTextColor(0);
        doc.text(gap.gap, margin + 30, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        const descLines = doc.splitTextToSize(gap.description, contentWidth);
        doc.text(descLines.slice(0, 2), margin, y);
        y += descLines.slice(0, 2).length * 3.5 + 6;
        doc.setFontSize(9);
      });
    }
  }

  // === PAGE: Your Next Steps ===
  if (data.viability.hypothesisConfidence) {
    addPageFooter();
    doc.addPage();
    pageNumber++;
    y = 30;
    addPageHeader();

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text('Your Next Steps', margin, y);
    y += 15;

    const confidence = data.viability.hypothesisConfidence;
    const level = confidence.level;

    // Status badge and title based on confidence level
    let statusColor: [number, number, number];
    let statusText: string;
    let title: string;
    let subtitle: string;
    let steps: { action: string; detail: string }[];
    let interviewTip: string;

    if (level === 'high') {
      statusColor = COLORS.success;
      statusText = 'PROCEED';
      title = 'Proceed to Customer Interviews';
      subtitle = 'Strong evidence supports your hypothesis. Time to validate with real conversations.';
      steps = [
        { action: '1. Schedule 5-10 interviews', detail: 'Target your identified audience in communities where they gather' },
        { action: '2. Use the interview questions provided', detail: 'Focus on past behavior, not hypothetical future willingness' },
        { action: '3. Probe for current solutions', detail: 'What are they using today? What do they hate about it?' },
        { action: '4. Look for willingness-to-pay signals', detail: 'Have they spent money solving this? Would they pay for better?' },
      ];
      interviewTip = 'Focus questions on the specific problem you hypothesized. Probe for past behavior and spending.';
    } else if (level === 'partial') {
      statusColor = COLORS.warning;
      statusText = 'EXPLORE';
      title = 'Interview with Exploration';
      subtitle = 'Your hypothesis has some support, but adjacent problems may be stronger.';

      // Get adjacent themes for the detail
      const adjacentThemes = data.communityVoice?.themeAnalysis?.themes
        ?.filter((t: { tier?: string }) => t.tier === 'contextual')
        .map((t: { name: string }) => t.name)
        .slice(0, 2) || [];

      steps = [
        {
          action: '1. Interview about your hypothesis AND adjacent themes',
          detail: adjacentThemes.length > 0 ? `Explore: ${adjacentThemes.join(', ')}` : 'Let conversations reveal which problems are most pressing'
        },
        { action: '2. Use open-ended discovery questions', detail: '"Walk me through a typical day..." and listen for pain points' },
        { action: '3. Be ready to pivot mid-interview', detail: 'If adjacent problems resonate more, explore them deeper' },
        { action: '4. Consider re-running research', detail: 'Try different keywords or a narrower audience definition' },
      ];
      interviewTip = 'Start with open discovery, then introduce your hypothesis. See if they bring up the problem naturally.';
    } else {
      statusColor = COLORS.danger;
      statusText = 'PIVOT';
      title = 'Consider Pivoting';
      subtitle = 'Your specific hypothesis wasn\'t prominent, but we found valuable adjacent insights.';

      const adjacentThemes = data.communityVoice?.themeAnalysis?.themes
        ?.filter((t: { tier?: string }) => t.tier === 'contextual')
        .map((t: { name: string }) => t.name)
        .slice(0, 3) || [];

      steps = [
        {
          action: '1. Review the adjacent opportunities',
          detail: adjacentThemes.length > 0 ? `Strong signals found for: ${adjacentThemes.join(', ')}` : 'Check the themes section for what IS being discussed'
        },
        { action: '2. Interview about what we FOUND', detail: 'Your original idea may emerge naturally in conversation' },
        { action: '3. Reframe your hypothesis', detail: 'Pivot the problem definition based on actual market signals' },
        { action: '4. Run a new search with the pivot', detail: 'Test the reframed hypothesis with fresh research' },
      ];
      interviewTip = 'Don\'t mention your original hypothesis. Ask broadly about challenges and see what emerges.';
    }

    // Status badge box
    doc.setFillColor(...statusColor);
    doc.roundedRect(margin, y, 60, 12, 3, 3, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(statusText, margin + 30, y + 8, { align: 'center' });
    doc.setTextColor(0);
    y += 20;

    // Title and subtitle
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.darkGray);
    doc.text(title, margin, y);
    y += 8;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    doc.text(subtitle, margin, y);
    doc.setTextColor(0);
    y += 15;

    // Steps
    steps.forEach(step => {
      checkNewPage(25);

      // Step number circle
      doc.setFillColor(240, 245, 255);
      doc.circle(margin + 8, y + 2, 6, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.primary);
      doc.text(step.action.charAt(0), margin + 5.5, y + 5);

      // Action text
      doc.setTextColor(...COLORS.darkGray);
      doc.text(step.action.substring(3), margin + 18, y + 4);
      y += 7;

      // Detail text
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.gray);
      const detailLines = doc.splitTextToSize(step.detail, contentWidth - 18);
      doc.text(detailLines.slice(0, 2), margin + 18, y);
      doc.setTextColor(0);
      y += detailLines.slice(0, 2).length * 4 + 8;
    });

    // Interview tip box
    checkNewPage(30);
    y += 5;
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(margin, y, contentWidth, 25, 3, 3, 'F');
    y += 10;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.success);
    doc.text('INTERVIEW TIP', margin + 5, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(0);
    const tipLines = doc.splitTextToSize(interviewTip, contentWidth - 10);
    doc.text(tipLines.slice(0, 2), margin + 5, y);
  }

  // Final footer
  addPageFooter();

  return doc;
}

// Helper to trigger download
export function downloadPDFReport(data: ReportData, filename?: string): void {
  const doc = generatePDFReport(data);
  const safeName = filename || `pvre-report-${data.hypothesis.slice(0, 30).replace(/[^a-z0-9]/gi, '-')}`;
  doc.save(`${safeName}.pdf`);
}
