/**
 * PDF Report Generator for PVRE Research Results
 * Generates comprehensive PDF reports from research data.
 */

import jsPDF from 'jspdf';
import type { CommunityVoiceResult } from '@/app/api/research/community-voice/route';
import type { CompetitorIntelligenceResult } from '@/app/api/research/competitor-intelligence/route';
import type { ViabilityVerdict } from '@/lib/analysis/viability-calculator';

export interface ReportData {
  hypothesis: string;
  createdAt: string;
  viability: ViabilityVerdict;
  communityVoice?: CommunityVoiceResult;
  competitors?: CompetitorIntelligenceResult;
}

// Color palette
const COLORS = {
  primary: [59, 130, 246] as [number, number, number],      // Blue
  success: [34, 197, 94] as [number, number, number],       // Green
  warning: [234, 179, 8] as [number, number, number],       // Yellow
  danger: [239, 68, 68] as [number, number, number],        // Red
  orange: [249, 115, 22] as [number, number, number],       // Orange
  gray: [107, 114, 128] as [number, number, number],        // Gray
  lightGray: [243, 244, 246] as [number, number, number],   // Light gray
  darkGray: [55, 65, 81] as [number, number, number],       // Dark gray
};

export function generatePDFReport(data: ReportData): jsPDF {
  const doc = new jsPDF();
  let y = 20;
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;
  let pageNumber = 1;

  // Helper function for text wrapping
  const addWrappedText = (text: string, fontSize: number, maxWidth: number = contentWidth) => {
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.45) + 4;
  };

  // Helper for new page check
  const checkNewPage = (neededSpace: number = 40) => {
    if (y > pageHeight - neededSpace) {
      addPageFooter();
      doc.addPage();
      pageNumber++;
      y = 30;
      addPageHeader();
    }
  };

  // Add page header (except first page)
  const addPageHeader = () => {
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 0, pageWidth, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text('PVRE Research Report', margin, 15);
    doc.setTextColor(0);
  };

  // Add page footer with page number
  const addPageFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text(`Page ${pageNumber}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text('Generated by PVRE - Pre-Validation Research Engine', margin, pageHeight - 10);
    doc.setTextColor(0);
  };

  // Draw score bar
  const drawScoreBar = (score: number, maxScore: number, x: number, barY: number, width: number, height: number = 8) => {
    const percentage = score / maxScore;
    const color = percentage >= 0.7 ? COLORS.success :
                  percentage >= 0.5 ? COLORS.warning :
                  percentage >= 0.3 ? COLORS.orange : COLORS.danger;

    // Background
    doc.setFillColor(...COLORS.lightGray);
    doc.roundedRect(x, barY, width, height, 2, 2, 'F');

    // Fill
    doc.setFillColor(...color);
    const fillWidth = Math.max(width * percentage, 4);
    doc.roundedRect(x, barY, fillWidth, height, 2, 2, 'F');
  };

  // Add section header
  const addSectionHeader = (title: string, icon?: string) => {
    checkNewPage(50);
    y += 5;
    doc.setFillColor(...COLORS.lightGray);
    doc.rect(margin - 5, y - 5, contentWidth + 10, 12, 'F');
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.darkGray);
    doc.text(icon ? `${icon}  ${title}` : title, margin, y + 3);
    doc.setTextColor(0);
    y += 15;
  };

  // === PAGE 1: Executive Summary ===

  // Header accent bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 6, 'F');

  y = 25;
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Research Report', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.gray);
  doc.text(`Generated: ${data.createdAt}`, margin, y);
  y += 15;

  // Hypothesis box - modern card design with accent border
  const accentWidth = 4;
  const innerPadding = 15;
  doc.setFontSize(10);
  const hypothesisLines = doc.splitTextToSize(data.hypothesis, contentWidth - accentWidth - (innerPadding * 2) - 5);
  const lineHeight = 5;
  const hypothesisBoxHeight = 12 + (hypothesisLines.length * lineHeight) + 12;

  // Main box background
  doc.setFillColor(250, 251, 252);
  doc.setDrawColor(230, 232, 236);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentWidth, hypothesisBoxHeight, 4, 4, 'FD');

  // Left accent bar (primary color)
  doc.setFillColor(...COLORS.primary);
  doc.roundedRect(margin, y, accentWidth, hypothesisBoxHeight, 4, 0, 'F');
  doc.rect(margin + 2, y, 2, hypothesisBoxHeight, 'F'); // Square off inner edge

  // Label
  y += 10;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gray);
  doc.text('HYPOTHESIS', margin + accentWidth + innerPadding, y);

  // Hypothesis text
  y += 6;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(hypothesisLines, margin + accentWidth + innerPadding, y);
  y += hypothesisLines.length * lineHeight + 8;

  // Viability Verdict Box
  const verdictColor = data.viability.verdict === 'strong' ? COLORS.success :
                       data.viability.verdict === 'mixed' ? COLORS.warning :
                       data.viability.verdict === 'weak' ? COLORS.orange :
                       COLORS.danger;

  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...verdictColor);
  doc.setLineWidth(2);
  doc.roundedRect(margin, y, contentWidth, 55, 4, 4, 'FD');

  y += 12;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gray);
  doc.text('VIABILITY VERDICT', margin + 10, y);

  // Big score
  y += 15;
  doc.setFontSize(36);
  doc.setTextColor(...verdictColor);
  doc.text(`${data.viability.overallScore.toFixed(1)}`, margin + 10, y);

  doc.setFontSize(14);
  doc.text('/10', margin + 35, y);

  // Verdict label
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(data.viability.verdictLabel, margin + 60, y - 5);

  // Score bar
  drawScoreBar(data.viability.overallScore, 10, margin + 60, y + 2, contentWidth - 70, 6);

  y += 15;
  doc.setTextColor(0);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const descLines = doc.splitTextToSize(data.viability.verdictDescription, contentWidth - 20);
  doc.text(descLines.slice(0, 2), margin + 10, y);
  y += 25;

  // Dimension scores grid
  y += 5;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Dimension Breakdown', margin, y);
  y += 10;

  const dimColWidth = contentWidth / 2;
  data.viability.dimensions.forEach((dim, i) => {
    const col = i % 2;
    const xPos = margin + col * dimColWidth;

    if (col === 0 && i > 0) y += 22;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    doc.text(`${dim.name} (${Math.round(dim.weight * 100)}%)`, xPos, y);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(`${dim.score.toFixed(1)}/10`, xPos + dimColWidth - 35, y);

    // Mini score bar
    drawScoreBar(dim.score, 10, xPos, y + 3, dimColWidth - 40, 5);
  });
  y += 30;

  // Dealbreakers
  if (data.viability.dealbreakers.length > 0) {
    checkNewPage(50);
    doc.setFillColor(254, 242, 242);
    doc.setDrawColor(...COLORS.danger);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentWidth, 8 + data.viability.dealbreakers.length * 8, 3, 3, 'FD');

    y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.danger);
    doc.text('DEALBREAKERS', margin + 5, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(0);
    data.viability.dealbreakers.forEach(db => {
      const lines = doc.splitTextToSize(`• ${db}`, contentWidth - 15);
      doc.text(lines[0], margin + 5, y);
      y += 7;
    });
    y += 10;
  }

  // Recommendations
  if (data.viability.recommendations.length > 0) {
    checkNewPage(60);
    addSectionHeader('Recommendations');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    data.viability.recommendations.forEach((rec, i) => {
      checkNewPage(20);
      const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, contentWidth);
      doc.text(lines, margin, y);
      y += lines.length * 4 + 4;
    });
  }

  // === PAGE 2: Community Voice (if available) ===
  if (data.communityVoice) {
    addPageFooter();
    doc.addPage();
    pageNumber++;
    y = 30;
    addPageHeader();

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text('Community Voice Analysis', margin, y);
    y += 15;

    // Pain Summary Cards
    const painSummary = data.communityVoice.painSummary;
    const cardWidth = (contentWidth - 10) / 3;

    // Total Signals card
    doc.setFillColor(...COLORS.lightGray);
    doc.roundedRect(margin, y, cardWidth, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text('Total Signals', margin + 5, y + 8);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.darkGray);
    doc.text(String(painSummary.totalSignals), margin + 5, y + 20);

    // High Intensity card
    doc.setFillColor(254, 242, 242);
    doc.roundedRect(margin + cardWidth + 5, y, cardWidth, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.danger);
    doc.text('High Intensity', margin + cardWidth + 10, y + 8);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(String(painSummary.highIntensityCount), margin + cardWidth + 10, y + 20);

    // WTP Signals card
    doc.setFillColor(236, 253, 245);
    doc.roundedRect(margin + (cardWidth + 5) * 2, y, cardWidth, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.success);
    doc.text('WTP Signals', margin + (cardWidth + 5) * 2 + 5, y + 8);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(String(painSummary.willingnessToPayCount), margin + (cardWidth + 5) * 2 + 5, y + 20);

    y += 35;

    // Top Subreddits
    addSectionHeader('Top Subreddits');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);
    painSummary.topSubreddits.slice(0, 5).forEach(sub => {
      doc.text(`r/${sub.name}`, margin, y);
      doc.text(`${sub.count} signals`, margin + 80, y);
      y += 6;
    });
    y += 5;

    // Themes
    if (data.communityVoice.themeAnalysis?.themes) {
      addSectionHeader('Top Pain Themes');
      doc.setFontSize(9);
      data.communityVoice.themeAnalysis.themes.slice(0, 4).forEach(theme => {
        checkNewPage(30);
        doc.setFont('helvetica', 'bold');
        const intensityColor = theme.intensity === 'high' ? COLORS.danger :
                              theme.intensity === 'medium' ? COLORS.warning : COLORS.gray;
        doc.setTextColor(...intensityColor);
        doc.text(`[${theme.intensity.toUpperCase()}]`, margin, y);
        doc.setTextColor(0);
        doc.text(theme.name, margin + 25, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        const descLines = doc.splitTextToSize(theme.description, contentWidth);
        doc.text(descLines.slice(0, 2), margin, y);
        y += descLines.slice(0, 2).length * 4 + 6;
      });
    }

    // Key Quotes
    if (data.communityVoice.themeAnalysis?.keyQuotes && data.communityVoice.themeAnalysis.keyQuotes.length > 0) {
      checkNewPage(60);
      addSectionHeader('Key Quotes');
      doc.setFontSize(9);
      data.communityVoice.themeAnalysis.keyQuotes.slice(0, 3).forEach(q => {
        checkNewPage(25);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, y - 3, contentWidth, 18, 2, 2, 'F');
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...COLORS.darkGray);
        const quoteLines = doc.splitTextToSize(`"${q.quote}"`, contentWidth - 10);
        doc.text(quoteLines.slice(0, 2), margin + 5, y + 3);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.gray);
        doc.text(`— ${q.source}`, margin + 5, y + 13);
        doc.setTextColor(0);
        doc.setFontSize(9);
        y += 22;
      });
    }

    // Market Sizing
    if (data.communityVoice.marketSizing) {
      checkNewPage(80);
      addSectionHeader('Market Sizing (TAM/SAM/SOM)');
      const ms = data.communityVoice.marketSizing;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');

      // TAM
      doc.setFont('helvetica', 'bold');
      doc.text('TAM:', margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.tam.value.toLocaleString()} potential customers`, margin + 25, y);
      y += 5;
      doc.setTextColor(...COLORS.gray);
      doc.text(ms.tam.description, margin + 25, y);
      doc.setTextColor(0);
      y += 8;

      // SAM
      doc.setFont('helvetica', 'bold');
      doc.text('SAM:', margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.sam.value.toLocaleString()} serviceable customers`, margin + 25, y);
      y += 5;
      doc.setTextColor(...COLORS.gray);
      doc.text(ms.sam.description, margin + 25, y);
      doc.setTextColor(0);
      y += 8;

      // SOM
      doc.setFont('helvetica', 'bold');
      doc.text('SOM:', margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.som.value.toLocaleString()} obtainable customers`, margin + 25, y);
      y += 5;
      doc.setTextColor(...COLORS.gray);
      doc.text(ms.som.description, margin + 25, y);
      doc.setTextColor(0);
      y += 12;

      // MSC Analysis
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(margin, y, contentWidth, 22, 2, 2, 'F');
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.text('To reach your MSC:', margin + 5, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${ms.mscAnalysis.customersNeeded.toLocaleString()} customers needed (${ms.mscAnalysis.penetrationRequired.toFixed(1)}% penetration)`, margin + 60, y);
      y += 7;
      const achieveColor = ms.mscAnalysis.achievability === 'highly_achievable' || ms.mscAnalysis.achievability === 'achievable'
        ? COLORS.success : ms.mscAnalysis.achievability === 'challenging' ? COLORS.warning : COLORS.danger;
      doc.setTextColor(...achieveColor);
      doc.text(`Achievability: ${ms.mscAnalysis.achievability.replace('_', ' ')}`, margin + 5, y);
      doc.setTextColor(0);
      y += 15;
    }

    // Timing
    if (data.communityVoice.timing) {
      checkNewPage(70);
      addSectionHeader('Timing Analysis');
      const timing = data.communityVoice.timing;

      // Score and trend
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Score: ${timing.score.toFixed(1)}/10`, margin, y);
      const trendColor = timing.trend === 'rising' ? COLORS.success :
                         timing.trend === 'stable' ? COLORS.warning : COLORS.danger;
      doc.setTextColor(...trendColor);
      doc.text(`Trend: ${timing.trend}`, margin + 50, y);
      doc.setTextColor(0);
      doc.text(`Window: ${timing.timingWindow}`, margin + 100, y);
      y += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      addWrappedText(timing.verdict, 9);
      y += 3;

      // Tailwinds
      if (timing.tailwinds.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.success);
        doc.text('Tailwinds:', margin, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        timing.tailwinds.slice(0, 3).forEach(tw => {
          const text = `+ ${tw.signal}: ${tw.description.slice(0, 70)}${tw.description.length > 70 ? '...' : ''}`;
          doc.text(text, margin + 5, y);
          y += 6;
        });
      }

      // Headwinds
      if (timing.headwinds.length > 0) {
        y += 3;
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.danger);
        doc.text('Headwinds:', margin, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        timing.headwinds.slice(0, 3).forEach(hw => {
          const text = `- ${hw.signal}: ${hw.description.slice(0, 70)}${hw.description.length > 70 ? '...' : ''}`;
          doc.text(text, margin + 5, y);
          y += 6;
        });
      }
    }

    // Interview Questions
    if (data.communityVoice.interviewQuestions) {
      addPageFooter();
      doc.addPage();
      pageNumber++;
      y = 30;
      addPageHeader();

      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.primary);
      doc.text('Interview Questions', margin, y);
      y += 5;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.gray);
      doc.text('Based on "The Mom Test" principles - focus on past behavior, not hypotheticals', margin, y);
      doc.setTextColor(0);
      y += 15;

      const sections = [
        { title: 'Context Questions', questions: data.communityVoice.interviewQuestions.contextQuestions, color: COLORS.primary },
        { title: 'Problem Exploration', questions: data.communityVoice.interviewQuestions.problemQuestions, color: COLORS.orange },
        { title: 'Solution Testing', questions: data.communityVoice.interviewQuestions.solutionQuestions, color: COLORS.success }
      ];

      sections.forEach(section => {
        checkNewPage(50);
        doc.setFillColor(...section.color);
        doc.rect(margin, y, 3, 10, 'F');
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.darkGray);
        doc.text(section.title, margin + 8, y + 7);
        y += 15;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        section.questions.forEach((q, i) => {
          checkNewPage(15);
          const lines = doc.splitTextToSize(`${i + 1}. ${q}`, contentWidth - 10);
          doc.text(lines, margin + 5, y);
          y += lines.length * 4 + 4;
        });
        y += 8;
      });
    }
  }

  // === PAGE: Competitors (if available) ===
  if (data.competitors) {
    addPageFooter();
    doc.addPage();
    pageNumber++;
    y = 30;
    addPageHeader();

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text('Competitive Landscape', margin, y);
    y += 15;

    // Competition Score
    if (data.competitors.competitionScore) {
      const cs = data.competitors.competitionScore;
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(margin, y, contentWidth, 30, 3, 3, 'F');

      y += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.gray);
      doc.text('COMPETITION SCORE', margin + 5, y);

      const scoreColor = cs.score >= 7 ? COLORS.success : cs.score >= 5 ? COLORS.warning : cs.score >= 3 ? COLORS.orange : COLORS.danger;
      doc.setFontSize(24);
      doc.setTextColor(...scoreColor);
      doc.text(`${cs.score.toFixed(1)}/10`, margin + 75, y);

      drawScoreBar(cs.score, 10, margin + 110, y - 6, contentWidth - 120, 8);

      y += 10;
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.gray);
      doc.text(`Data quality: ${cs.confidence}`, margin + 5, y);
      doc.setTextColor(0);
      y += 15;
    }

    // Market Overview
    if (data.competitors.marketOverview) {
      addSectionHeader('Market Overview');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      addWrappedText(data.competitors.marketOverview.summary, 9);
      doc.text(`Market Maturity: ${data.competitors.marketOverview.maturityLevel}`, margin, y);
      y += 10;
    }

    // Competitors
    addSectionHeader('Key Competitors');

    data.competitors.competitors.slice(0, 5).forEach(comp => {
      checkNewPage(45);

      // Threat level color bar
      const threatColor = comp.threatLevel === 'high' ? COLORS.danger :
                         comp.threatLevel === 'medium' ? COLORS.warning : COLORS.success;
      doc.setFillColor(...threatColor);
      doc.rect(margin, y, 3, 25, 'F');

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text(comp.name, margin + 8, y + 5);

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...threatColor);
      doc.text(`${comp.threatLevel} threat`, margin + 8 + doc.getTextWidth(comp.name) + 5, y + 5);
      doc.setTextColor(0);

      y += 10;
      doc.setFontSize(8);
      const descLines = doc.splitTextToSize(comp.description, contentWidth - 15);
      doc.text(descLines.slice(0, 2), margin + 8, y);
      y += descLines.slice(0, 2).length * 3.5 + 3;

      if (comp.strengths && comp.strengths.length > 0) {
        doc.setTextColor(...COLORS.success);
        doc.text('+ ' + comp.strengths.slice(0, 2).join(', ').slice(0, 80), margin + 8, y);
        y += 5;
      }
      if (comp.weaknesses && comp.weaknesses.length > 0) {
        doc.setTextColor(...COLORS.danger);
        doc.text('- ' + comp.weaknesses.slice(0, 2).join(', ').slice(0, 80), margin + 8, y);
        y += 5;
      }
      doc.setTextColor(0);
      y += 8;
    });

    // Gap Analysis
    if (data.competitors.gaps && data.competitors.gaps.length > 0) {
      checkNewPage(60);
      addSectionHeader('Market Gaps & Opportunities');
      doc.setFontSize(9);
      data.competitors.gaps.slice(0, 4).forEach(gap => {
        checkNewPage(25);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.success);
        doc.text(`[${gap.opportunity.toUpperCase()}]`, margin, y);
        doc.setTextColor(0);
        doc.text(gap.gap, margin + 30, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        const descLines = doc.splitTextToSize(gap.description, contentWidth);
        doc.text(descLines.slice(0, 2), margin, y);
        y += descLines.slice(0, 2).length * 3.5 + 6;
        doc.setFontSize(9);
      });
    }
  }

  // Final footer
  addPageFooter();

  return doc;
}

// Helper to trigger download
export function downloadPDFReport(data: ReportData, filename?: string): void {
  const doc = generatePDFReport(data);
  const safeName = filename || `pvre-report-${data.hypothesis.slice(0, 30).replace(/[^a-z0-9]/gi, '-')}`;
  doc.save(`${safeName}.pdf`);
}
