export {
  generateEmbedding,
  generateEmbeddings,
  cosineSimilarity,
  classifySimilarity,
  compareSimilarities,
  filterBySimilarity,
  generateMultiFacetEmbeddings,
  maxSimilarityAcrossFacets,
  filterByMultiFacetSimilarity,
  isEmbeddingServiceAvailable,
  SIMILARITY_THRESHOLDS,
  type EmbeddingResult,
  type SimilarityResult,
  type SimilarityTier,
} from './embedding-service'
