'use client'

import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'
import {
  CheckCircle2,
  Calculator,
  Sparkles,
  AlertTriangle,
  Database,
  ExternalLink,
} from 'lucide-react'

// General source reliability types
export type DataSourceType = 'verified' | 'calculated' | 'estimate' | 'ai_estimate' | 'unverified'

// Specific data sources for attribution
export type SpecificSource =
  | 'reddit'
  | 'arctic_shift'
  | 'google_trends'
  | 'google_play'
  | 'app_store'
  | 'trustpilot'
  | 'hacker_news'
  | 'claude_ai'

interface DataSourceBadgeProps {
  type: DataSourceType
  source?: SpecificSource  // Optional specific source attribution
  className?: string
  showLabel?: boolean  // Default true, set false for compact mode
  size?: 'sm' | 'md'  // Badge size
}

interface SourceConfig {
  icon: React.ReactNode
  label: string
  shortLabel: string  // For compact mode
  color: string
  tooltip: string
}

const typeConfig: Record<DataSourceType, Omit<SourceConfig, 'shortLabel'>> = {
  verified: {
    icon: <CheckCircle2 className="h-3 w-3" />,
    label: 'VERIFIED',
    color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800',
    tooltip: 'Data retrieved directly from source API (Reddit, App Store)',
  },
  calculated: {
    icon: <Calculator className="h-3 w-3" />,
    label: 'CALCULATED',
    color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400 border-blue-200 dark:border-blue-800',
    tooltip: 'Derived from verified data using a formula',
  },
  estimate: {
    icon: <Sparkles className="h-3 w-3" />,
    label: 'ESTIMATE',
    color: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400 border-amber-200 dark:border-amber-800',
    tooltip: 'Estimated value — may differ from actual',
  },
  ai_estimate: {
    icon: <Sparkles className="h-3 w-3" />,
    label: 'AI ESTIMATE',
    color: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400 border-amber-200 dark:border-amber-800',
    tooltip: 'AI-generated estimate — not independently verified. May vary 2-10x.',
  },
  unverified: {
    icon: <AlertTriangle className="h-3 w-3" />,
    label: 'UNVERIFIED',
    color: 'bg-slate-100 text-slate-600 dark:bg-slate-900/30 dark:text-slate-400 border-slate-200 dark:border-slate-700',
    tooltip: 'Source could not be verified — interpret with caution',
  },
}

const sourceLabels: Record<SpecificSource, { name: string; description: string }> = {
  reddit: { name: 'Reddit', description: 'Reddit community discussions' },
  arctic_shift: { name: 'Arctic Shift', description: 'Historical Reddit archive API' },
  google_trends: { name: 'Google Trends', description: 'Google search interest data' },
  google_play: { name: 'Google Play', description: 'Google Play Store reviews' },
  app_store: { name: 'App Store', description: 'Apple App Store reviews' },
  trustpilot: { name: 'Trustpilot', description: 'Trustpilot user reviews' },
  hacker_news: { name: 'Hacker News', description: 'Y Combinator community' },
  claude_ai: { name: 'Claude AI', description: 'Generated by Claude AI' },
}

export function DataSourceBadge({
  type,
  source,
  className,
  showLabel = true,
  size = 'sm'
}: DataSourceBadgeProps) {
  const config = typeConfig[type]
  const sourceInfo = source ? sourceLabels[source] : null

  const sizeClasses = size === 'md'
    ? 'px-2 py-1 text-xs'
    : 'px-1.5 py-0.5 text-[10px]'

  const tooltipContent = sourceInfo
    ? `${sourceInfo.description}\n\n${config.tooltip}`
    : config.tooltip

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <span
          className={cn(
            'inline-flex items-center gap-1 font-medium rounded border cursor-help',
            sizeClasses,
            config.color,
            className
          )}
        >
          {config.icon}
          {showLabel && (
            <span>
              {source ? sourceInfo?.name : config.label}
            </span>
          )}
        </span>
      </TooltipTrigger>
      <TooltipContent className="max-w-[250px]">
        <div className="space-y-1">
          {sourceInfo && (
            <p className="font-medium text-sm">{sourceInfo.name}</p>
          )}
          <p className="text-sm">{config.tooltip}</p>
        </div>
      </TooltipContent>
    </Tooltip>
  )
}

// =============================================================================
// Compound Badge with Source + Reliability
// =============================================================================

interface SourceAttributionBadgeProps {
  source: SpecificSource
  reliability: DataSourceType
  className?: string
}

/**
 * Shows both the specific source and its reliability level
 * e.g., "Arctic Shift ✓" or "Claude AI ⚠️"
 */
export function SourceAttributionBadge({
  source,
  reliability,
  className,
}: SourceAttributionBadgeProps) {
  const reliabilityConfig = typeConfig[reliability]
  const sourceInfo = sourceLabels[source]

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <span
          className={cn(
            'inline-flex items-center gap-1.5 px-2 py-1 text-xs font-medium rounded border cursor-help',
            reliabilityConfig.color,
            className
          )}
        >
          <Database className="h-3 w-3" />
          <span>{sourceInfo.name}</span>
          {reliabilityConfig.icon}
        </span>
      </TooltipTrigger>
      <TooltipContent className="max-w-[280px]">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Database className="h-4 w-4" />
            <span className="font-semibold">{sourceInfo.name}</span>
          </div>
          <p className="text-sm text-muted-foreground">{sourceInfo.description}</p>
          <div className="pt-1 border-t">
            <div className="flex items-center gap-1.5 text-sm">
              {reliabilityConfig.icon}
              <span>{reliabilityConfig.label}</span>
            </div>
            <p className="text-xs text-muted-foreground mt-0.5">{reliabilityConfig.tooltip}</p>
          </div>
        </div>
      </TooltipContent>
    </Tooltip>
  )
}

// =============================================================================
// Inline Data Transparency Indicator
// =============================================================================

interface DataTransparencyProps {
  verifiedCount: number
  estimatedCount: number
  calculatedCount?: number
  className?: string
}

/**
 * Shows a summary of data quality for a section
 * e.g., "3 verified · 2 AI estimates"
 */
export function DataTransparency({
  verifiedCount,
  estimatedCount,
  calculatedCount = 0,
  className,
}: DataTransparencyProps) {
  const total = verifiedCount + estimatedCount + calculatedCount
  if (total === 0) return null

  const verifiedPercent = Math.round((verifiedCount / total) * 100)

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <div className={cn(
          'inline-flex items-center gap-2 text-xs text-muted-foreground cursor-help',
          className
        )}>
          <span className="flex items-center gap-1">
            <CheckCircle2 className="h-3 w-3 text-emerald-600" />
            {verifiedCount} verified
          </span>
          {calculatedCount > 0 && (
            <span className="flex items-center gap-1">
              <Calculator className="h-3 w-3 text-blue-600" />
              {calculatedCount} calculated
            </span>
          )}
          {estimatedCount > 0 && (
            <span className="flex items-center gap-1">
              <Sparkles className="h-3 w-3 text-amber-600" />
              {estimatedCount} AI estimates
            </span>
          )}
        </div>
      </TooltipTrigger>
      <TooltipContent>
        <div className="space-y-1">
          <p className="font-medium text-sm">Data Quality Summary</p>
          <p className="text-sm">{verifiedPercent}% of metrics are verified from APIs</p>
          <p className="text-xs text-muted-foreground">
            Click individual badges for source details
          </p>
        </div>
      </TooltipContent>
    </Tooltip>
  )
}

// =============================================================================
// External Link Badge (for verifiable sources)
// =============================================================================

interface VerifyLinkProps {
  url: string
  source: string
  className?: string
}

/**
 * Link to verify data at source
 */
export function VerifyLink({ url, source, className }: VerifyLinkProps) {
  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className={cn(
        'inline-flex items-center gap-1 text-xs text-emerald-600 hover:text-emerald-700 hover:underline',
        className
      )}
    >
      <ExternalLink className="h-3 w-3" />
      Verify on {source}
    </a>
  )
}
