'use client'

import { cn } from '@/lib/utils'
import { Check, Calculator, Bot, Info } from 'lucide-react'
import { Tooltip, TooltipTrigger, TooltipContent } from '@/components/ui/tooltip'

export type TrustLevel = 'verified' | 'calculated' | 'ai-estimate'

interface TrustBadgeProps {
  level: TrustLevel
  label?: string
  tooltip?: string
  size?: 'sm' | 'md'
  className?: string
}

const trustConfig: Record<TrustLevel, {
  icon: typeof Check
  text: string
  tooltip: string
  bgClass: string
  textClass: string
  borderClass: string
}> = {
  verified: {
    icon: Check,
    text: 'Verified',
    tooltip: 'Quote verified - found in original source (Reddit post, app review, or discussion)',
    bgClass: 'bg-emerald-50 dark:bg-emerald-950/30',
    textClass: 'text-emerald-700 dark:text-emerald-400',
    borderClass: 'border-emerald-200 dark:border-emerald-800',
  },
  calculated: {
    icon: Calculator,
    text: 'Calculated',
    tooltip: 'Derived from verified data using transparent formulas',
    bgClass: 'bg-blue-50 dark:bg-blue-950/30',
    textClass: 'text-blue-700 dark:text-blue-400',
    borderClass: 'border-blue-200 dark:border-blue-800',
  },
  'ai-estimate': {
    icon: Bot,
    text: 'AI Estimate',
    tooltip: 'Generated by AI based on patterns. Verify independently before making decisions.',
    bgClass: 'bg-amber-50 dark:bg-amber-950/30',
    textClass: 'text-amber-700 dark:text-amber-400',
    borderClass: 'border-amber-300 dark:border-amber-700 border-dashed',
  },
}

export function TrustBadge({
  level,
  label,
  tooltip,
  size = 'sm',
  className
}: TrustBadgeProps) {
  const config = trustConfig[level]
  const Icon = config.icon
  const displayTooltip = tooltip ?? config.tooltip

  const sizeClasses = size === 'sm'
    ? 'text-[10px] px-1.5 py-0.5 gap-1'
    : 'text-xs px-2 py-1 gap-1.5'

  const iconSize = size === 'sm' ? 'w-3 h-3' : 'w-3.5 h-3.5'

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <span
          className={cn(
            'inline-flex items-center rounded-md border font-medium uppercase tracking-wide cursor-help',
            sizeClasses,
            config.bgClass,
            config.textClass,
            config.borderClass,
            className
          )}
        >
          <Icon className={iconSize} />
          <span>{label ?? config.text}</span>
        </span>
      </TooltipTrigger>
      <TooltipContent side="top" className="max-w-[250px]">
        {displayTooltip}
      </TooltipContent>
    </Tooltip>
  )
}

// Wrapper component for sections that need trust indication
interface TrustSectionProps {
  level: TrustLevel
  children: React.ReactNode
  showBadge?: boolean
  className?: string
}

export function TrustSection({
  level,
  children,
  showBadge = true,
  className
}: TrustSectionProps) {
  const config = trustConfig[level]

  return (
    <div
      className={cn(
        'relative rounded-lg border p-4',
        config.borderClass,
        level === 'ai-estimate' && 'border-dashed',
        className
      )}
    >
      {showBadge && (
        <div className="absolute -top-2.5 left-3">
          <TrustBadge level={level} />
        </div>
      )}
      <div className={showBadge ? 'pt-1' : ''}>
        {children}
      </div>
    </div>
  )
}
